export const ecolesDoctorales = [
    { id: 'EDAM', label: 'Doctorat (Manufacturing (edoc))' },
    { id: 'EDAR', label: 'Doctorat (Architecture et sciences de la ville (edoc))' },
    { id: 'EDBB', label: 'Doctorat (Biotechnologie et génie biologique (edoc))' },
    { id: 'EDCB', label: 'Doctorat (Biologie computationnelle et quantitative (edoc))' },
    { id: 'EDCE', label: 'Doctorat (Génie civil et environnement (edoc))' },
    { id: 'EDCH', label: 'Doctorat (Chimie et génie chimique (edoc))' },
    { id: 'EDDH', label: 'Doctorat (Humanités digitales (edoc))' },
    { id: 'EDEE', label: 'Doctorat (Génie électrique (edoc))' },
    { id: 'EDEY', label: 'Doctorat (Energie (edoc))' },
    { id: 'EDFI', label: 'Doctorat (Finance (edoc))' },
    { id: 'EDIC', label: 'Doctorat (Informatique et communications (edoc))' },
    { id: 'EDMA', label: 'Doctorat (Mathématiques (edoc))' },
    { id: 'EDME', label: 'Doctorat (Mécanique (edoc))' },
    { id: 'EDMI', label: 'Doctorat (Microsystèmes et microélectronique (edoc))' },
    { id: 'EDMS', label: 'Doctorat (Approches moléculaires du vivant (edoc))' },
    { id: 'EDMT', label: 'Doctorat (Management de la technologie (edoc))' },
    { id: 'EDMX', label: 'Doctorat (Science et génie des matériaux (edoc))' },
    { id: 'EDNE', label: 'Doctorat (Neurosciences (edoc))' },
    { id: 'EDPO', label: 'Doctorat (Photonique (edoc))' },
    { id: 'EDPY', label: 'Doctorat (Physique (edoc))' },
    { id: 'EDRS', label: 'Doctorat (Robotique, contrôle et systèmes intelligents (edoc))' },
    { id: 'JDPLS', label: 'Doctorat (Learning Sciences (edoc))' }
]
